"""Contracts for the complete locked dependency-audit export."""

from __future__ import annotations

import json
import sys
from pathlib import Path

import pytest
from scripts.run_dependency_audit import (
    EXPORT_ARGUMENTS,
    DependencyAuditError,
    build_pip_audit_command,
    load_exclusions,
    prepare_audit_requirements,
    run_export,
)

ROOT = Path(__file__).resolve().parents[1]
ALLOWLIST = ROOT / "config/dependency-audit-exclusions.json"


def _write_allowlist(path: Path, *, extra: dict[str, object] | None = None) -> None:
    payload: dict[str, object] = {
        "schema_version": 1,
        "excluded_lock_packages": [
            {
                "name": "ancestryllm",
                "source": {"editable": "."},
                "export_requirement": "-e .",
                "reason": (
                    "The editable workspace root has no pinned registry artifact for "
                    "pip-audit; every resolved dependency remains included."
                ),
            }
        ],
    }
    if extra:
        payload.update(extra)
    path.write_text(json.dumps(payload), encoding="utf-8")


def _write_lock(path: Path) -> None:
    path.write_text(
        """\
version = 1

[[package]]
name = "ancestryllm"
version = "0.5.0"
source = { editable = "." }

[[package]]
name = "demo_pkg"
version = "1.2.3"
source = { registry = "https://pypi.org/simple" }

[[package]]
name = "transitive"
version = "4.5.6"
source = { registry = "https://pypi.org/simple" }
""",
        encoding="utf-8",
    )


def _valid_export() -> str:
    return """\
# generated by the exact locked export command
-e .
demo-pkg==1.2.3 \\
    --hash=sha256:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
transitive==4.5.6 \\
    --hash=sha256:bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
"""


def test_complete_export_matches_lock_and_removes_only_documented_editable(
    tmp_path: Path,
) -> None:
    lock_path = tmp_path / "uv.lock"
    allowlist_path = tmp_path / "allowlist.json"
    _write_lock(lock_path)
    _write_allowlist(allowlist_path)

    prepared = prepare_audit_requirements(
        lock_path,
        _valid_export(),
        load_exclusions(allowlist_path),
    )

    assert prepared.exported_pairs == {
        ("demo-pkg", "1.2.3"),
        ("transitive", "4.5.6"),
    }
    assert prepared.excluded_pairs == {("ancestryllm", "0.5.0")}
    assert "-e ." not in prepared.requirements_text
    assert "demo-pkg==1.2.3" in prepared.requirements_text
    assert "transitive==4.5.6" in prepared.requirements_text


@pytest.mark.parametrize(
    ("export_text", "failure_code"),
    [
        (
            _valid_export().replace("transitive==4.5.6", "unlocked==9.9.9"),
            "DEPAUDIT_EXPORT_LOCK_MISMATCH",
        ),
        (
            _valid_export().replace("transitive==4.5.6 \\\n", ""),
            "DEPAUDIT_EXPORT_LOCK_MISMATCH",
        ),
        (
            _valid_export().replace("-e .\n", "-e ../other-project\n"),
            "DEPAUDIT_EXPORT_UNSUPPORTED_ENTRY",
        ),
        (
            _valid_export() + "    disguised-package==9.9.9\n",
            "DEPAUDIT_EXPORT_UNSUPPORTED_ENTRY",
        ),
        (
            _valid_export().replace(
                "demo-pkg==1.2.3 \\\n",
                "demo-pkg==1.2.3 --index-url https://example.invalid/simple \\\n",
            ),
            "DEPAUDIT_EXPORT_UNSUPPORTED_ENTRY",
        ),
    ],
)
def test_export_fails_closed_for_missing_extra_or_unapproved_entries(
    tmp_path: Path,
    export_text: str,
    failure_code: str,
) -> None:
    lock_path = tmp_path / "uv.lock"
    allowlist_path = tmp_path / "allowlist.json"
    _write_lock(lock_path)
    _write_allowlist(allowlist_path)

    with pytest.raises(DependencyAuditError) as raised:
        prepare_audit_requirements(
            lock_path,
            export_text,
            load_exclusions(allowlist_path),
        )

    assert raised.value.code == failure_code


def test_export_fails_closed_for_duplicate_pinned_requirement(tmp_path: Path) -> None:
    lock_path = tmp_path / "uv.lock"
    allowlist_path = tmp_path / "allowlist.json"
    _write_lock(lock_path)
    _write_allowlist(allowlist_path)
    duplicate_export = (
        _valid_export()
        + "demo-pkg==1.2.3 \\\n"
        + "    --hash=sha256:cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc\n"
    )

    with pytest.raises(DependencyAuditError) as raised:
        prepare_audit_requirements(
            lock_path,
            duplicate_export,
            load_exclusions(allowlist_path),
        )

    assert raised.value.code == "DEPAUDIT_EXPORT_DUPLICATE"


def test_export_accepts_uv_environment_markers(tmp_path: Path) -> None:
    lock_path = tmp_path / "uv.lock"
    allowlist_path = tmp_path / "allowlist.json"
    _write_lock(lock_path)
    _write_allowlist(allowlist_path)
    marked_export = _valid_export().replace(
        "demo-pkg==1.2.3 \\\n",
        "demo-pkg==1.2.3 ; sys_platform == 'darwin' or os_name == 'nt' \\\n",
    )

    prepared = prepare_audit_requirements(
        lock_path,
        marked_export,
        load_exclusions(allowlist_path),
    )

    assert ("demo-pkg", "1.2.3") in prepared.exported_pairs


def test_exclusion_schema_and_lock_source_are_strict(tmp_path: Path) -> None:
    lock_path = tmp_path / "uv.lock"
    allowlist_path = tmp_path / "allowlist.json"
    _write_lock(lock_path)

    _write_allowlist(allowlist_path, extra={"schema_version": 2})
    with pytest.raises(DependencyAuditError) as schema_error:
        load_exclusions(allowlist_path)
    assert schema_error.value.code == "DEPAUDIT_ALLOWLIST_SCHEMA_UNSUPPORTED"

    _write_allowlist(allowlist_path, extra={"unknown": True})
    with pytest.raises(DependencyAuditError) as fields_error:
        load_exclusions(allowlist_path)
    assert fields_error.value.code == "DEPAUDIT_ALLOWLIST_FIELDS_INVALID"

    _write_allowlist(allowlist_path)
    altered_lock = lock_path.read_text(encoding="utf-8").replace(
        'source = { editable = "." }',
        'source = { registry = "https://pypi.org/simple" }',
    )
    lock_path.write_text(altered_lock, encoding="utf-8")
    with pytest.raises(DependencyAuditError) as source_error:
        prepare_audit_requirements(
            lock_path,
            _valid_export(),
            load_exclusions(allowlist_path),
        )
    assert source_error.value.code == "DEPAUDIT_ALLOWLIST_LOCK_MISMATCH"


def test_repository_export_covers_every_group_extra_and_transitive() -> None:
    uv_binary = ROOT / ".tools/uv" / ("uv.exe" if sys.platform == "win32" else "uv")
    export_text = run_export(uv_binary, ROOT)
    prepared = prepare_audit_requirements(
        ROOT / "uv.lock",
        export_text,
        load_exclusions(ALLOWLIST),
    )

    names = {name for name, _version in prepared.exported_pairs}
    assert {
        "anthropic",  # provider extra
        "pyinstaller",  # desktop-build extra
        "ruff",  # lint group
        "ty",  # typecheck group and advisory checker
        "pytest",  # test group
        "pip-audit",  # security group
        "uv-build",  # build group
        "pypi-attestations",  # release-verifier group
        "urllib3",  # representative transitive dependency
    } <= names
    assert prepared.excluded_pairs == {("ancestryllm", "0.6.0")}


def test_make_runs_exact_export_then_hash_locked_pip_audit() -> None:
    makefile = (ROOT / "Makefile").read_text(encoding="utf-8")
    assert EXPORT_ARGUMENTS == (
        "export",
        "--locked",
        "--all-extras",
        "--all-groups",
    )
    assert (
        "$(UV_BIN) run --locked --group security python "
        "scripts/run_dependency_audit.py --uv $(UV_BIN)" in makefile
    )

    command = build_pip_audit_command(Path("requirements.txt"))
    assert command == (
        sys.executable,
        "-m",
        "pip_audit",
        "--strict",
        "--require-hashes",
        "--disable-pip",
        "-r",
        "requirements.txt",
    )
