"""Deterministic adversarial characterization for the pure GEDCOM engine."""

from __future__ import annotations

import codecs
import json
from collections.abc import Callable, Iterable, Sequence
from itertools import product
from pathlib import Path

import pytest

from ancestryllm.core.errors import FileIngressError
from ancestryllm.gedcom import identity, serialization
from ancestryllm.gedcom import parser as gm

FIXTURES = Path(__file__).parent / "fixtures" / "gedcom_adversarial"
MANIFEST = FIXTURES / "manifest.json"
EXPECTED_DISPOSITIONS = {"accepted", "accepted-with-findings", "rejected"}
GENERATED_FACTORIES = {
    "deep_graph_variant",
    "encoded_input_variants",
    "invalid_output_variants",
    "malformed_byte_variants",
    "malformed_line_variants",
    "semantic_property_variants",
    "utf8_line_boundary_variants",
}


def _minimal_text(
    *,
    version: str = "5.5.5",
    newline: str = "\n",
    name: str = "Zoë /Fiction/",
) -> str:
    """Return one fictional, structurally minimal GEDCOM document."""
    lines = [
        "0 HEAD",
        "1 SOUR AdversarialFactory",
        "1 GEDC",
        f"2 VERS {version}",
        "1 CHAR UTF-8",
        "0 @I1@ INDI",
        f"1 NAME {name}",
        "0 TRLR",
    ]
    return newline.join(lines) + newline


def _write_bytes(tmp_path: Path, name: str, payload: bytes) -> Path:
    """Write a generated byte fixture only inside pytest's temporary directory."""
    path = tmp_path / name
    path.write_bytes(payload)
    return path


def _logical_lines(lines: Sequence[str]) -> tuple[tuple[int, str, str, str], ...]:
    """Canonicalize physical CONC/CONT wrapping into logical GEDCOM values."""
    logical: list[tuple[int, str, str, str]] = []
    for raw in lines:
        parsed = gm.parse_gedcom_line(raw)
        if parsed.tag in {"CONC", "CONT"} and logical and parsed.level == logical[-1][0] + 1:
            level, xref, tag, value = logical[-1]
            separator = "\n" if parsed.tag == "CONT" else ""
            logical[-1] = (level, xref, tag, value + separator + parsed.value)
        else:
            logical.append((parsed.level, parsed.xref, parsed.tag, parsed.value))
    return tuple(logical)


def _canonical_records(
    records: Iterable[gm.GedcomRecord],
    *,
    tags: frozenset[str],
) -> dict[tuple[str, str], tuple[tuple[int, str, str, str], ...]]:
    """Return order-independent logical records for semantic round-trip checks."""
    selected = [record for record in records if record.tag in tags]
    canonical = {(record.tag, record.pointer): _logical_lines(record.lines) for record in selected}
    assert len(canonical) == len(selected), "comparison corpus must use unique record keys"
    return canonical


def _record(source: gm.ParsedSource, tag: str, pointer: str) -> gm.GedcomRecord:
    """Find one record by semantic key in a parsed source."""
    return next(
        record for record in source.records if record.tag == tag and record.pointer == pointer
    )


def _valid_555_lines() -> list[str]:
    """Return a fresh valid 5.5.5 line list for validator mutations."""
    return [
        "0 HEAD",
        "1 SOUR AdversarialFactory",
        "1 GEDC",
        "2 VERS 5.5.5",
        "1 CHAR UTF-8",
        "0 @I1@ INDI",
        "1 NAME Aster /Fiction/",
        "0 TRLR",
    ]


def test_manifest_is_a_complete_fictional_catalog() -> None:
    catalog = json.loads(MANIFEST.read_text(encoding="utf-8"))

    assert catalog["schema_version"] == 1
    assert catalog["data_policy"] == "fictional-only"
    entries = catalog["entries"]
    ids = [entry["id"] for entry in entries]
    assert len(ids) == len(set(ids))
    assert {entry["expected"] for entry in entries} == EXPECTED_DISPOSITIONS

    referenced_files: set[str] = set()
    referenced_factories: set[str] = set()
    for entry in entries:
        source = entry["source"]
        assert entry["covers"]
        assert entry["stage"]
        assert source["kind"] in {"file", "file-set", "factory"}
        if source["kind"] == "factory":
            referenced_factories.add(source["factory"])
        else:
            referenced_files.update(source["paths"])

    assert referenced_factories == GENERATED_FACTORIES
    assert referenced_files == {
        "minimal-551.ged",
        "minimal-555.ged",
        "preserve-extensions.ged",
        "xref-source-a.ged",
        "xref-source-b.ged",
    }
    assert all((FIXTURES / relative_path).is_file() for relative_path in referenced_files)


@pytest.mark.parametrize(
    ("fixture_name", "version"),
    [("minimal-555.ged", "5.5.5"), ("minimal-551.ged", "5.5.1")],
)
def test_committed_minimal_versions_parse(fixture_name: str, version: str) -> None:
    records = list(gm.iter_gedcom_records(FIXTURES / fixture_name))

    assert [record.tag for record in records] == ["HEAD", "INDI", "TRLR"]
    assert f"2 VERS {version}" in records[0].lines
    assert records[1].pointer == "@I1@"


@pytest.mark.parametrize(
    ("case_name", "payload"),
    [
        ("utf8.ged", _minimal_text().encode("utf-8")),
        ("utf8-bom.ged", codecs.BOM_UTF8 + _minimal_text().encode("utf-8")),
        (
            "utf16le-bom.ged",
            codecs.BOM_UTF16_LE + _minimal_text().encode("utf-16-le"),
        ),
        (
            "utf16be-bom.ged",
            codecs.BOM_UTF16_BE + _minimal_text().encode("utf-16-be"),
        ),
        ("crlf.ged", _minimal_text(newline="\r\n").encode("utf-8")),
    ],
)
def test_generated_encoding_and_newline_variants_parse(
    tmp_path: Path,
    case_name: str,
    payload: bytes,
) -> None:
    path = _write_bytes(tmp_path, case_name, payload)

    records = list(gm.iter_gedcom_records(path))

    assert [record.tag for record in records] == ["HEAD", "INDI", "TRLR"]
    assert gm.parse_gedcom_line(records[1].lines[1]).value == "Zoë /Fiction/"


@pytest.mark.parametrize(
    "line",
    [
        "",
        "-1 NAME invalid",
        "00 HEAD",
        "01 NAME invalid",
        "100 NOTE invalid",
        "1",
        "1NAME invalid",
        "1 @I 1@ INDI",
        "0 @I1@",
        "0 @I1@@ INDI",
    ],
)
def test_malformed_line_grammar_is_rejected(line: str) -> None:
    with pytest.raises(gm.GedcomParseError):
        gm.parse_gedcom_line(line, 7)


@pytest.mark.parametrize(
    ("case_name", "payload"),
    [
        ("invalid-utf8.ged", b"0 HEAD\n1 NOTE \xff\n0 TRLR\n"),
        ("utf16le-no-bom.ged", _minimal_text().encode("utf-16-le")),
        ("partial-bom.ged", b"\xff0 HEAD\n0 TRLR\n"),
    ],
)
def test_generated_malformed_bytes_are_rejected(
    tmp_path: Path,
    case_name: str,
    payload: bytes,
) -> None:
    path = _write_bytes(tmp_path, case_name, payload)

    with pytest.raises(FileIngressError) as raised:
        list(gm.iter_gedcom_records(path))

    assert raised.value.code == "FILE_ENCODING_INVALID"


def test_extensions_alternatives_and_continuations_are_preserved() -> None:
    source = gm.load_sources([FIXTURES / "preserve-extensions.ged"])[0]
    individual = _record(source, "INDI", "@I1@")
    family = _record(source, "FAM", "@F1@")

    assert "1 NAME Zoë /Fiction/" in individual.lines
    assert "1 NAME Zed /Alternative/" in individual.lines
    assert "1 _VENDOR alpha" in individual.lines
    assert "2 _NESTED" in individual.lines
    assert "3 NOTE preserved detail" in individual.lines
    assert "2 TYPE" in individual.lines
    assert individual.lines.count("1 BIRT") == 2
    assert "2 DATE 01 JAN 2000" in individual.lines
    assert "2 _ORIGDATE 1 JAN 2000" in individual.lines
    assert "2 PLAC Fictional Vale" in individual.lines
    assert individual.lines.count("1 DEAT") == 2
    assert "2 DATE BEF 2099" in individual.lines
    assert "2 DATE AFT 2099" in individual.lines
    assert "1 SOUR @S1@" in individual.lines
    assert "2 NOTE @N1@" in individual.lines
    assert "2 OBJE @O1@" in individual.lines
    assert "2 CITN Fictional citation detail" in individual.lines
    assert "3 NOTE Unicode note: 星" in individual.lines
    assert "1 _EMPTY" in family.lines
    assert (
        _logical_lines(["1 NOTE first", "2 CONC -joined", "2 CONT next line"])[0][3]
        == "first-joined\nnext line"
    )
    assert "2 DATE definitely not a date" in individual.lines
    assert identity.normalise_gedcom_date("definitely not a date") == "definitely not a date"
    assert _record(source, "SOUR", "@S1@").lines == [
        "0 @S1@ SOUR",
        "1 TITL Fictional Archive Catalogue",
        "1 NOTE @N1@",
        "1 OBJE @O1@",
    ]
    assert "1 FILE fictional-portrait.jpg" in _record(source, "OBJE", "@O1@").lines


def test_xref_collisions_and_dangling_references_are_namespaced_per_source() -> None:
    source_a, source_b = gm.load_sources(
        [FIXTURES / "xref-source-a.ged", FIXTURES / "xref-source-b.ged"]
    )

    assert source_a.pointer_map["@I1@"] == "@I1@"
    assert source_a.pointer_map["@F1@"] == "@F1@"
    assert source_a.pointer_map["@I99@"] == "@I99@"
    assert source_b.pointer_map["@I1@"] not in {"@I1@", "@I99@"}
    assert source_b.pointer_map["@F1@"] != "@F1@"

    person_a = _record(source_a, "INDI", "@I1@")
    family_a = _record(source_a, "FAM", "@F1@")
    person_b = _record(source_b, "INDI", source_b.pointer_map["@I1@"])
    family_b = _record(source_b, "FAM", source_b.pointer_map["@F1@"])

    assert "1 _TEXT literal @I1@ and @I99@" in person_a.lines
    assert "1 CHIL @I99@" in family_a.lines
    assert "1 _TEXT literal @I1@" in person_b.lines
    assert f"1 FAMS {source_b.pointer_map['@F1@']}" in person_b.lines
    assert f"1 HUSB {source_b.pointer_map['@I1@']}" in family_b.lines


def test_literal_xref_text_does_not_reserve_a_later_record_pointer(tmp_path: Path) -> None:
    source_a = tmp_path / "literal-source.ged"
    source_b = tmp_path / "record-source.ged"
    source_a.write_text(
        _minimal_text().replace(
            "1 NAME Zoë /Fiction/",
            "1 NAME Zoë /Fiction/\n1 _TEXT literal @I9@",
        ),
        encoding="utf-8",
    )
    source_b.write_text(
        _minimal_text()
        .replace("@I1@", "@I9@")
        .replace(
            "Zoë /Fiction/",
            "Aster /Fiction/",
        ),
        encoding="utf-8",
    )

    literal_source, record_source = gm.load_sources([source_a, source_b])

    assert "@I9@" not in literal_source.pointer_map
    assert record_source.pointer_map["@I9@"] == "@I9@"
    assert "1 _TEXT literal @I9@" in _record(literal_source, "INDI", "@I1@").lines


@pytest.mark.parametrize(
    ("line", "expected_line_count"),
    [
        ("1 NOTE " + "x" * 247, 1),
        ("1 NOTE " + "x" * 248, 1),
        ("1 NOTE " + "x" * 249, 2),
        ("1 NOTE " + "é" * 125, 2),
        ("1 NOTE " + "🙂" * 63, 2),
    ],
)
def test_utf8_line_wrapping_preserves_logical_value(
    line: str,
    expected_line_count: int,
) -> None:
    original = gm.parse_gedcom_line(line)

    wrapped = serialization.wrap_long_gedcom_lines([line])

    assert len(wrapped) == expected_line_count
    assert all(len(physical.encode("utf-8")) <= 255 for physical in wrapped)
    assert _logical_lines(wrapped) == ((1, "", "NOTE", original.value),)


def test_level_99_value_that_requires_wrapping_is_rejected() -> None:
    with pytest.raises(gm.GedcomParseError, match="level 99"):
        serialization.wrap_long_gedcom_lines(["99 NOTE " + "x" * 248])


def _without_version(lines: list[str]) -> list[str]:
    return [line for line in lines if not line.startswith("2 VERS")]


def _without_charset(lines: list[str]) -> list[str]:
    return [line for line in lines if not line.startswith("1 CHAR")]


ValidatorMutation = Callable[[list[str]], list[str]]


@pytest.mark.parametrize(
    ("case_name", "mutate"),
    [
        ("empty", lambda _lines: []),
        ("missing-head", lambda lines: lines[1:]),
        ("missing-trailer", lambda lines: lines[:-1]),
        ("duplicate-head", lambda lines: [*lines[:-1], "0 HEAD", lines[-1]]),
        ("duplicate-trailer", lambda lines: [*lines, "0 TRLR"]),
        (
            "duplicate-xref",
            lambda lines: [*lines[:-1], "0 @I1@ NOTE duplicate", lines[-1]],
        ),
        ("missing-version", _without_version),
        (
            "unsupported-version",
            lambda lines: [line.replace("2 VERS 5.5.5", "2 VERS 5.5.1") for line in lines],
        ),
        ("missing-charset", _without_charset),
        (
            "wrong-charset",
            lambda lines: [line.replace("1 CHAR UTF-8", "1 CHAR ANSEL") for line in lines],
        ),
        (
            "lowercase-tag",
            lambda lines: [line.replace("1 NAME", "1 name") for line in lines],
        ),
        (
            "tag-too-long",
            lambda lines: [*lines[:-1], "1 " + "_" * 32, lines[-1]],
        ),
        (
            "line-too-long",
            lambda lines: [*lines[:-1], "1 NOTE " + "x" * 249, lines[-1]],
        ),
        (
            "xref-below-level-zero",
            lambda lines: [*lines[:-1], "1 @I2@ INDI", lines[-1]],
        ),
        (
            "invalid-xref",
            lambda lines: [*lines[:-1], "0 @1@ INDI", lines[-1]],
        ),
        (
            "skipped-level",
            lambda lines: [*lines[:-1], "3 NOTE skipped", lines[-1]],
        ),
        (
            "record-after-trailer",
            lambda lines: [*lines, "0 @I2@ INDI"],
        ),
    ],
)
def test_555_validator_rejects_invalid_output_structures(
    case_name: str,
    mutate: ValidatorMutation,
) -> None:
    del case_name
    with pytest.raises(gm.GedcomParseError):
        gm.validate_gedcom_555(mutate(_valid_555_lines()))


def test_555_validator_preserves_semantic_anomalies_for_quality_findings() -> None:
    lines = [
        *_valid_555_lines()[:-1],
        "1 BIRT",
        "2 DATE definitely not a date",
        "1 FAMS @F404@",
        "0 @I2@ INDI",
        "1 FAMS @F1@",
        "0 @I3@ INDI",
        "0 @F1@ FAM",
        "1 HUSB @I2@",
        "1 CHIL @I2@",
        "0 @F2@ FAM",
        "0 TRLR",
    ]

    gm.validate_gedcom_555(lines)


def test_555_validator_accepts_a_deep_acyclic_family_graph() -> None:
    depth = 64
    lines = _valid_555_lines()[:5]
    for index in range(1, depth + 1):
        lines.extend(
            [
                f"0 @I{index}@ INDI",
                f"1 NAME Fictional {index} /Chain/",
            ]
        )
        if index > 1:
            lines.append(f"1 FAMC @F{index - 1}@")
        if index < depth:
            lines.append(f"1 FAMS @F{index}@")
    for index in range(1, depth):
        lines.extend(
            [
                f"0 @F{index}@ FAM",
                f"1 HUSB @I{index}@",
                f"1 CHIL @I{index + 1}@",
            ]
        )
    lines.append("0 TRLR")

    gm.validate_gedcom_555(lines)


PROPERTY_CASES = tuple(
    (name, note)
    for name, note in product(
        ("Aster /Fiction/", "Zoë /Fiction/", "示例 /Fiction/"),
        ("short fictional note", "é" * 140),
    )
)


@pytest.mark.parametrize(("name", "note"), PROPERTY_CASES)
def test_semantic_property_corpus_survives_serialize_reparse(
    tmp_path: Path,
    name: str,
    note: str,
) -> None:
    source_path = tmp_path / "property-source.ged"
    source_path.write_text(
        "\n".join(
            [
                "0 HEAD",
                "1 SOUR AdversarialPropertyFactory",
                "1 GEDC",
                "2 VERS 5.5.5",
                "1 CHAR UTF-8",
                "0 @I1@ INDI",
                f"1 NAME {name}",
                "1 NAME Alias /Alternative/",
                "2 TYPE alias",
                "1 _VENDOR retained",
                "2 _NESTED retained",
                f"1 NOTE {note}",
                "1 FAMS @F1@",
                "0 @F1@ FAM",
                "1 HUSB @I1@",
                "1 CHIL @I404@",
                "0 @N1@ NOTE detached fictional note",
                "1 _DETAIL retained",
                "0 TRLR",
                "",
            ]
        ),
        encoding="utf-8",
    )
    source = gm.load_sources([source_path])[0]
    expected = _canonical_records(
        source.records,
        tags=frozenset({"INDI", "FAM", "NOTE"}),
    )
    people = [
        identity.individual_from_record(record) for record in source.records if record.tag == "INDI"
    ]
    output = tmp_path / "property-output.ged"

    serialization.write_gedcom(people, output, source_documents=[source])

    emitted_records = list(gm.iter_gedcom_records(output))
    gm.validate_gedcom_555([line for record in emitted_records for line in record.lines])
    assert (
        _canonical_records(
            emitted_records,
            tags=frozenset({"INDI", "FAM", "NOTE"}),
        )
        == expected
    )
