/** Creates and retains bounded, privacy-safe desktop diagnostic events. */
import { randomUUID } from 'node:crypto'
import {
  appendFileSync,
  lstatSync,
  mkdirSync,
  renameSync,
  rmSync,
  type Stats,
} from 'node:fs'
import { join } from 'node:path'

/** Version shared by Electron main, Python core, and the packaged Flask sidecar. */
export const DESKTOP_DIAGNOSTIC_SCHEMA_VERSION = 'ancestryllm.desktop-diagnostic/1'

/** Diagnostic components permitted to persist local events. */
export type DesktopDiagnosticComponent = 'electron-main' | 'python-core' | 'flask-sidecar'
/** Stable severities available to the versioned event contract. */
export type DesktopDiagnosticSeverity = 'debug' | 'info' | 'warning' | 'error'
/** Metadata deliberately excludes strings so paths, prompts, names, and secrets cannot be stored. */
export type DesktopDiagnosticMetadataValue = boolean | number | null
/** Bounded metadata attached to one stable diagnostic code. */
export type DesktopDiagnosticMetadata = Readonly<Record<string, DesktopDiagnosticMetadataValue>>

/** One versioned diagnostic event safe for local persistence and support export. */
export interface DesktopDiagnosticEvent {
  schema_version: typeof DESKTOP_DIAGNOSTIC_SCHEMA_VERSION
  timestamp: string
  run_id: string
  code: string
  severity: DesktopDiagnosticSeverity
  component: DesktopDiagnosticComponent
  app_version: string
  metadata: DesktopDiagnosticMetadata
}

/** Input accepted by the event factory; timestamps are generated by the trusted caller. */
export interface DesktopDiagnosticEventInput {
  runId: string
  appVersion: string
  code: string
  severity: DesktopDiagnosticSeverity
  component: DesktopDiagnosticComponent
  metadata?: DesktopDiagnosticMetadata
  now?: Date
}

/** Configuration for one component-specific JSONL writer. */
export interface DesktopDiagnosticWriterOptions {
  directory: string
  runId: string
  appVersion: string
  component: DesktopDiagnosticComponent
  maxBytes?: number
  maxFiles?: number
}

const RUN_ID_PATTERN = /^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/
const CODE_PATTERN = /^[A-Z][A-Z0-9_]{2,63}$/
const VERSION_PATTERN = /^[0-9A-Za-z][0-9A-Za-z.+-]{0,31}$/
const METADATA_KEY_PATTERN = /^[a-z][a-z0-9_]{0,31}$/
const SENSITIVE_METADATA_KEY_FRAGMENT = /(?:content|database|email|error|exception|family|gedcom|key|message|name|path|person|prompt|query|secret|stack|token|url)/
const TIMESTAMP_PATTERN = /^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\.\d{3}Z$/
const COMPONENTS = new Set<DesktopDiagnosticComponent>([
  'electron-main',
  'python-core',
  'flask-sidecar',
])
const SEVERITIES = new Set<DesktopDiagnosticSeverity>([
  'debug',
  'info',
  'warning',
  'error',
])

/** Maximum encoded bytes for one newline-delimited event. */
export const MAX_DESKTOP_DIAGNOSTIC_EVENT_BYTES = 4096
/** Default maximum size of one active component log before rotation. */
export const DEFAULT_DESKTOP_DIAGNOSTIC_MAX_BYTES = 512 * 1024
/** Default total files retained per component, including the active file. */
export const DEFAULT_DESKTOP_DIAGNOSTIC_MAX_FILES = 3

/** Creates a non-identifying UUIDv4 correlation identifier for one desktop run. */
export function createDesktopDiagnosticRunId(): string {
  return randomUUID()
}

function requireSafeInteger(value: number, label: string): void {
  if (!Number.isSafeInteger(value) || value < -1_000_000_000 || value > 1_000_000_000) {
    throw new Error(`${label} must be a bounded integer.`)
  }
}

function normalizeMetadata(
  metadata: DesktopDiagnosticMetadata | undefined,
): DesktopDiagnosticMetadata {
  const entries = Object.entries(metadata ?? {})
  if (entries.length > 8) throw new Error('Diagnostic metadata exceeded its entry limit.')
  const normalized: Record<string, DesktopDiagnosticMetadataValue> = {}
  for (const [key, value] of entries) {
    if (!METADATA_KEY_PATTERN.test(key) || SENSITIVE_METADATA_KEY_FRAGMENT.test(key)) {
      throw new Error('Diagnostic metadata contains a prohibited key.')
    }
    if (typeof value === 'string' || typeof value === 'object' && value !== null) {
      throw new Error('Diagnostic metadata contains a prohibited value.')
    }
    if (typeof value === 'number') requireSafeInteger(value, 'Diagnostic metadata')
    if (value !== null && typeof value !== 'boolean' && typeof value !== 'number') {
      throw new Error('Diagnostic metadata contains a prohibited value.')
    }
    normalized[key] = value
  }
  return Object.freeze(normalized)
}

/** Validates and freezes one exact event without accepting errors, paths, or free-form text. */
export function createDesktopDiagnosticEvent(
  input: DesktopDiagnosticEventInput,
): Readonly<DesktopDiagnosticEvent> {
  if (!RUN_ID_PATTERN.test(input.runId)) throw new Error('Invalid diagnostic run identifier.')
  if (!VERSION_PATTERN.test(input.appVersion)) throw new Error('Invalid diagnostic app version.')
  if (!CODE_PATTERN.test(input.code)) throw new Error('Invalid diagnostic code.')
  if (!COMPONENTS.has(input.component)) throw new Error('Invalid diagnostic component.')
  if (!SEVERITIES.has(input.severity)) throw new Error('Invalid diagnostic severity.')
  const timestamp = (input.now ?? new Date()).toISOString()
  if (!TIMESTAMP_PATTERN.test(timestamp)) throw new Error('Invalid diagnostic timestamp.')
  const event: DesktopDiagnosticEvent = {
    schema_version: DESKTOP_DIAGNOSTIC_SCHEMA_VERSION,
    timestamp,
    run_id: input.runId,
    code: input.code,
    severity: input.severity,
    component: input.component,
    app_version: input.appVersion,
    metadata: normalizeMetadata(input.metadata),
  }
  if (Buffer.byteLength(JSON.stringify(event), 'utf8') > MAX_DESKTOP_DIAGNOSTIC_EVENT_BYTES) {
    throw new Error('Diagnostic event exceeded its encoded size limit.')
  }
  return Object.freeze(event)
}

function requirePositiveInteger(value: number, label: string): number {
  if (!Number.isSafeInteger(value) || value <= 0) {
    throw new Error(`${label} must be a positive integer.`)
  }
  return value
}

function fileMetadata(path: string): Stats | undefined {
  try {
    return lstatSync(path)
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code === 'ENOENT') return undefined
    throw error
  }
}

function isRegularOwnedFile(metadata: Stats): boolean {
  return metadata.isFile() && !metadata.isSymbolicLink()
}

function isOwnedDirectory(metadata: Stats): boolean {
  return metadata.isDirectory() && !metadata.isSymbolicLink()
}

/**
 * Writes one component-specific JSONL stream with bounded rotation.
 *
 * Every public operation catches filesystem and validation failures so
 * diagnostics can never change application startup, recovery, or shutdown.
 */
export class DesktopDiagnosticWriter {
  private readonly activePath: string
  private readonly maxBytes: number
  private readonly maxFiles: number

  constructor(private readonly options: DesktopDiagnosticWriterOptions) {
    this.maxBytes = requirePositiveInteger(
      options.maxBytes ?? DEFAULT_DESKTOP_DIAGNOSTIC_MAX_BYTES,
      'Diagnostic maxBytes',
    )
    this.maxFiles = requirePositiveInteger(
      options.maxFiles ?? DEFAULT_DESKTOP_DIAGNOSTIC_MAX_FILES,
      'Diagnostic maxFiles',
    )
    this.activePath = join(options.directory, `${options.component}.jsonl`)
  }

  /** Attempts to persist one event and returns false without throwing on any failure. */
  write(
    code: string,
    severity: DesktopDiagnosticSeverity,
    metadata: DesktopDiagnosticMetadata = {},
  ): boolean {
    try {
      const event = createDesktopDiagnosticEvent({
        runId: this.options.runId,
        appVersion: this.options.appVersion,
        component: this.options.component,
        code,
        severity,
        metadata,
      })
      const line = `${JSON.stringify(event)}\n`
      const encodedBytes = Buffer.byteLength(line, 'utf8')
      if (encodedBytes > this.maxBytes) return false
      mkdirSync(this.options.directory, { recursive: true, mode: 0o700 })
      const directoryMetadata = fileMetadata(this.options.directory)
      if (!directoryMetadata || !isOwnedDirectory(directoryMetadata)) return false
      const activeMetadata = fileMetadata(this.activePath)
      if (activeMetadata && !isRegularOwnedFile(activeMetadata)) return false
      const currentBytes = activeMetadata?.size ?? 0
      if (currentBytes + encodedBytes > this.maxBytes) this.rotate()
      appendFileSync(this.activePath, line, { encoding: 'utf8', mode: 0o600, flag: 'a' })
      return true
    } catch {
      return false
    }
  }

  /** Removes only this component's active and rotated diagnostic files. */
  clear(): boolean {
    try {
      const directoryMetadata = fileMetadata(this.options.directory)
      if (!directoryMetadata) return true
      if (!isOwnedDirectory(directoryMetadata)) return false
      for (let index = 0; index < this.maxFiles; index += 1) {
        const path = index === 0 ? this.activePath : `${this.activePath}.${index}`
        const metadata = fileMetadata(path)
        if (!metadata) continue
        if (!isRegularOwnedFile(metadata)) return false
        rmSync(path)
      }
      return true
    } catch {
      return false
    }
  }

  private rotate(): void {
    const activeMetadata = fileMetadata(this.activePath)
    if (this.maxFiles === 1) {
      if (activeMetadata) {
        if (!isRegularOwnedFile(activeMetadata)) throw new Error('Unsafe diagnostic active file.')
        rmSync(this.activePath)
      }
      return
    }
    const oldest = `${this.activePath}.${this.maxFiles - 1}`
    const oldestMetadata = fileMetadata(oldest)
    if (oldestMetadata) {
      if (!isRegularOwnedFile(oldestMetadata)) {
        throw new Error('Unsafe diagnostic rotation target.')
      }
      rmSync(oldest)
    }
    for (let index = this.maxFiles - 2; index >= 1; index -= 1) {
      const source = `${this.activePath}.${index}`
      const sourceMetadata = fileMetadata(source)
      if (!sourceMetadata) continue
      if (!isRegularOwnedFile(sourceMetadata)) {
        throw new Error('Unsafe diagnostic rotation source.')
      }
      renameSync(source, `${this.activePath}.${index + 1}`)
    }
    if (activeMetadata) {
      if (!isRegularOwnedFile(activeMetadata)) throw new Error('Unsafe diagnostic active file.')
      renameSync(this.activePath, `${this.activePath}.1`)
    }
  }
}
